# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SERVERHOST }}
        username: ${{ secrets.SERVERUSERNAME }}
        password: ${{ secrets.SERVERPASSWORD }}
        protocol: ftps
        port: 22
        server-dir: ~/VoiceGroove
        
    - name: 🚀 Run
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVERHOST }}
        username: ${{ secrets.SERVERUSERNAME }}
        password: ${{ secrets.SERVERPASSWORD }}
        port: 22
        script: |
          cd ~/VoiceGroove
          pnpm pm2
